- hosts: spark 
  sudo: true

  tasks:
    - name: install required packages 
      yum: pkg={{item}} state=installed
      with_items:
        - docker-io
        - unzip 
        - java-1.8.0-openjdk-devel
        - python-docker-py

    - name: get spark 
      get_url: url='http://mirror.vorboss.net/apache/spark/spark-1.4.0/spark-1.4.0-bin-hadoop2.6.tgz' dest='/usr/local/spark.tgz'

    - name: extract spark
      unarchive: src='/usr/local/spark.tgz' dest='/usr/local/' copy=no

    - name: symlink for spark
      file: src=/usr/local/spark-1.4.0-bin-hadoop2.6/ dest=/usr/local/spark state=link

- hosts: master 
  sudo: true

  tasks:
    - name: start master
      shell: /usr/local/spark/sbin/start-master.sh --webui-port 9080
      environment:
        SPARK_MASTER_IP: "{{ ansible_eth0.ipv4.address }}" 
     
    - name: start docker service
      service: name=docker state=started

    - name: start gossip router
      docker:
        image: gustavonalle/jgroups-gossip
        ports: "12001:12001"
        state: started
    

- hosts: slave 
  sudo: true
  
  tasks:
    - name: start slave 
      shell: "/usr/local/spark/sbin/start-slave.sh spark://{{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address'] }}:7077 --webui-port 9081"


- hosts: infinispan 
  sudo: true

  tasks:
    - name: copy infinispan server
      copy: src=/home/gfernandes/.m2/repository/org/infinispan/server/infinispan-server/8.0.0-SNAPSHOT/infinispan-server-8.0.0-SNAPSHOT-bin.zip dest=/usr/local/infinispan-server-8.0.0-SNAPSHOT-bin.zip

    - name: extract infinispan 
      unarchive: src='/usr/local/infinispan-server-8.0.0-SNAPSHOT-bin.zip' dest='/usr/local/' copy=no
    
    - name: symlink for infinispan
      file: src=/usr/local/infinispan-server-8.0.0-SNAPSHOT/ dest=/usr/local/infinispan state=link

    - name: increase memory
      shell: "sed -i 's/-Xmx512/-Xmx4096/g' /usr/local/infinispan/bin/standalone.conf"     

    - name: configure gossip
      shell: sed -i '/MPING/c\<protocol type="TCPGOSSIP"><property name="initial_hosts">${gossip}</property></protocol>'  /usr/local/infinispan/standalone/configuration/clustered.xml

    - name: start infinispan
      shell: nohup /usr/local/infinispan/bin/standalone.sh -c clustered.xml -Djboss.default.jgroups.stack=tcp -Dgossip={{ hostvars[groups['master'][0]]['ansible_eth0']['ipv4']['address']  }}[12001] -Djgroups.bind_addr={{ ansible_eth0.ipv4.address  }} -Djboss.bind.address={{ ansible_eth0.ipv4.address }} &



